pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        //maven(url = "https://jitpack.io")
    }
}

include ':app'
rootProject.name = "Clean Pokedex"